"""Add PlRecord for DB P&L

Revision ID: 4e1b70ba366d
Revises: ce2f91d92660
Create Date: 2026-04-21 23:30:38.297484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e1b70ba366d'
down_revision: Union[str, Sequence[str], None] = 'ce2f91d92660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pl_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa', sa.String(), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('cuenta_id', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('ingresos_ordinarios', sa.Float(), nullable=True),
    sa.Column('costo_ventas', sa.Float(), nullable=True),
    sa.Column('depreciacion_operacional', sa.Float(), nullable=True),
    sa.Column('gastos_administracion', sa.Float(), nullable=True),
    sa.Column('depreciacion_amortizacion', sa.Float(), nullable=True),
    sa.Column('otros_ingresos', sa.Float(), nullable=True),
    sa.Column('otros_egresos', sa.Float(), nullable=True),
    sa.Column('ingresos_financieros', sa.Float(), nullable=True),
    sa.Column('costos_financieros', sa.Float(), nullable=True),
    sa.Column('diferencias_cambio', sa.Float(), nullable=True),
    sa.Column('resultado_unidades_reajuste', sa.Float(), nullable=True),
    sa.Column('impuestos_ganancias', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pl_empresa_periodo', 'pl_records', ['empresa', 'periodo'], unique=False)
    op.create_index(op.f('ix_pl_records_cuenta_id'), 'pl_records', ['cuenta_id'], unique=False)
    op.create_index(op.f('ix_pl_records_empresa'), 'pl_records', ['empresa'], unique=False)
    op.create_index(op.f('ix_pl_records_id'), 'pl_records', ['id'], unique=False)
    op.create_index(op.f('ix_pl_records_periodo'), 'pl_records', ['periodo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pl_records_periodo'), table_name='pl_records')
    op.drop_index(op.f('ix_pl_records_id'), table_name='pl_records')
    op.drop_index(op.f('ix_pl_records_empresa'), table_name='pl_records')
    op.drop_index(op.f('ix_pl_records_cuenta_id'), table_name='pl_records')
    op.drop_index('idx_pl_empresa_periodo', table_name='pl_records')
    op.drop_table('pl_records')
    # ### end Alembic commands ###
