"""Estructura_Base

Revision ID: ce2f91d92660
Revises: 
Create Date: 2026-04-21 23:00:57.022942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce2f91d92660'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('rut', sa.String(), nullable=True),
    sa.Column('es_consolidado', sa.Boolean(), nullable=True),
    sa.Column('id_matriz', sa.Integer(), nullable=True),
    sa.Column('moneda_funcional', sa.String(length=3), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_matriz'], ['company_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_entities_id'), 'company_entities', ['id'], unique=False)
    op.create_index(op.f('ix_company_entities_nombre'), 'company_entities', ['nombre'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_entities_nombre'), table_name='company_entities')
    op.drop_index(op.f('ix_company_entities_id'), table_name='company_entities')
    op.drop_table('company_entities')
    # ### end Alembic commands ###
